### PR TITLE
Updated .gitignore

### PR DESCRIPTION
**Pull request by samsrose**
Added some new stuff, removed some old stuff & reorganized the rest.
Thanks to Octocat for the ideas (https://gist.github.com/octocat/9257657)

### CODE REVIEW

**Comment by joelrip** [comment]
@samsrose Cool. Let's pretend I don't know WTF any of this does. :-) What do these changes do for us?

**Comment by roughani** [comment]
They prevent files with those extensions from being committed from peeps'
local machines to the remote repository. That way someone's junk editor
files don't add glut to the repo. If it's just the .gitignore, then it
should be a harmless commit.

**Comment by joelrip** [comment]
Done and done. Thanks!

**Comment by samsrose** [comment]
Sorry for the late reply. Primarily, the purpose of the .gitignore file is to exclude any files from development when creating a pull request/committing new content. As I’m updating features of the codebase on my end, I decided to just go ahead and upload the gitignore so when I do my future big pull request, it’s already there.

**Pull request merged**
